### ISSUE TITLE
Error fetching feature flags ReferenceError: AbortSignal is not defined

### ISSUE THREAD

**Issue by wedlex** [naskio/n8n-nodes-python#8]
Hello, I have an error message `Error fetching feature flags ReferenceError: AbortSignal is not defined` when using PythonFunction. The process freezes for 10 seconds, and the result of the test script is displayed correctly, but this error occurs in the log. 

Can it come from my nginx proxy manager reverse proxy?

Error 1:
```
Error fetching feature flags ReferenceError: AbortSignal is not defined
    at PostHog.<anonymous> (/usr/lib/node_modules/n8n/node_modules/posthog-core/src/index.ts:460:6)
    at step (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:102:23)
    at Object.next (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:83:53)
    at /usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:72:12)
    at PostHogCoreStateless.fetchWithRetry (/usr/lib/node_modules/n8n/node_modules/posthog-node/lib/index.cjs.js:1063:16)
    at PostHog.<anonymous> (/usr/lib/node_modules/n8n/node_modules/posthog-core/src/index.ts:219:17)
    at step (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:102:23)
    at Object.next (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:83:53)
    at /usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:72:12)
    at PostHogCoreStateless.getDecide (/usr/lib/node_modules/n8n/node_modules/posthog-node/lib/index.cjs.js:833:16)
    at PostHog.<anonymous> (/usr/lib/node_modules/n8n/node_modules/posthog-core/src/index.ts:318:39)
    at step (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:102:23)
    at Object.next (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:83:53)
    at /usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:72:12)
    at PostHogCoreStateless.getFeatureFlagsAndPayloadsStateless (/usr/lib/node_modules/n8n/node_modules/posthog-node/lib/index.cjs.js:950:16)
    at PostHog.<anonymous> (/usr/lib/node_modules/n8n/node_modules/posthog-core/src/index.ts:306:24)
    at step (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:102:23)
    at Object.next (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:83:53)
    at /usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/n8n/node_modules/node_modules/tslib/tslib.es6.js:72:12)
    at PostHog.call [as getFeatureFlagsStateless] (/usr/lib/node_modules/n8n/node_modules/posthog-node/lib/index.cjs.js:937:16)
    at PostHog.capture (/usr/lib/node_modules/n8n/node_modules/posthog-node/src/posthog-node.ts:106:38)
    at PostHogClient.track (/usr/lib/node_modules/n8n/src/posthog/index.ts:39:17)
    at /usr/lib/node_modules/n8n/src/telemetry/index.ts:193:20
    at new Promise (<anonymous>)
    at Telemetry.track (/usr/lib/node_modules/n8n/src/telemetry/index.ts:177:10)
    at InternalHooks.onWorkflowPostExecute (/usr/lib/node_modules/n8n/src/InternalHooks.ts:371:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Error 2:
`Could not initialize license manager sdk`

Test python script:
```
new_items = []
for item in items:
		item['newField'] = 'newValue'
		new_items.append(item)
return new_items # should return a list
```

I use this docker-compose file with portainer:
```
version: '3.8'

services:
  n8n:
    image: naskio/n8n-python:latest-debian # use this if intended to use heavy python packages
    #    image: naskio/n8n-python # alpine for light python packages
    #    command: /bin/sh -c "n8n start"
    restart: always
    container_name: n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Moscow
      - TZ=Europe/Moscow
      - N8N_HOST=n8n.[HIDE DOMAIN]
      - N8N_PROTOCOL=https
      - N8N_PORT=443
      - VUE_APP_URL_BASE_API=https://n8n.[HIDE DOMAIN]/
      - WEBHOOK_TUNNEL_URL=https://n8n.[HIDE DOMAIN]/
      - N8N_EDITOR_BASE_URL=https://n8n.[HIDE DOMAIN]/
      - DB_TYPE=mariadb
      - DB_MYSQLDB_HOST=mariadb
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_DATABASE=n8n
      - DB_MYSQLDB_USER=n8n
      - DB_MYSQLDB_PASSWORD=[HIDE PASSWORD]
    ports:
      - "127.0.0.1:5678:443"
      
    volumes:
      - /home/n8n_data:/home/node/
      - /home/n8n_data/local-files:/data # by default workdir == /data
      - /home/n8n_data/python_scripts:/data/py_scripts
      - /home/n8n_data/requirements.txt:/data/requirements
      
volumes:
  n8n_data:
  
networks:
  default:
    external: true
    name: evilcorp
```
